#!/bin/bash

if [ "$EUID" -ne 0 ] 
then echo "Please run as root"

else (
chmod +x bash.cack
cp bash.cack /usr/local/bin/cack
mkdir /usr/local/share/cack
cp -r cack.* /usr/local/share/cack/
)
fi
exit
